kind: pipeline
name: default

steps:
- name: test
  image: golang
  commands:
  - mkdir -p $GOPATH/src/github.com/mjarkk/
  - mv $(pwd) $GOPATH/src/github.com/mjarkk/wotnlclans
  - cd $GOPATH/src/github.com/mjarkk/wotnlclans
  - pwd
  when:
    branch:
    - v3
