kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/octocat/hello-world

steps:
- name: Build go files
  image: golang
  commands:
  - go get
  - go build
  when:
    branch:
    - v3
- name: Build web_static files
  image: kkarczmarczyk/node-yarn
  commands: 
  - ls
