kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/mjarkk/wotnlclans

steps:
- name: Build go files
  image: golang
  commands:
  - go get
  - go build
  when:
    branch:
    - v3
- name: Build web_static files
  image: kkarczmarczyk/node-yarn
  commands: 
  - cd web_static
  - yarn
  - yarn build
  when:
    branch:
    - v3
- name: Deploy
  image: karappo/dronedeploy:drone-0.8
  environment:
    SSH_KEY:
      from_secret: privateKey
    DEP_MASTER_COMMAND: rsync
    DEP_MASTER_HOST: mkopenga.com
    DEP_MASTER_USER: root
    DEP_MASTER_HOST_DIR: /var/www/wotnlclans
  commands: 
  - echo "$SSH_KEY" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
  - curl https://raw.githubusercontent.com/karappo/drone-deploy/drone-compatible/v0.8/deploy.sh | bash
  when:
    branch:
    - v3
 