kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/mjarkk/wotnlclans

steps:
- name: Build go files
  image: golang
  commands:
  - go get
  - go build
  when:
    branch:
    - v3
- name: Build web_static files
  image: kkarczmarczyk/node-yarn
  environment:
    PRIVATEKEY:
      from_secret: privateKey
    PUBLICKEY:
      from_secret: publicKey
    SSH: ssh -tt root@mkopenga.com
  commands: 
  - cd web_static
  - yarn
  - yarn build
- name: Deploy
  image: golang
  commands: 
  - mkdir ~/.ssh/
  - echo "$PRIVATEKEY" > ~/.ssh/id_rsa
  - echo "$PUBLICKEY" > ~/.ssh/id_rsa.pub
  - chmod 600 ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa.pub
  - eval `ssh-agent -s`
  - echo "$PRIVATEKEY" | ssh-add -
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - $SSH "pwd"
