kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/mjarkk/wotnlclans

steps:
- name: Build go files
  image: golang
  commands:
  - go get
  - go build
  when:
    branch:
    - v3
- name: Build web_static files
  image: kkarczmarczyk/node-yarn
  commands: 
  - cd web_static
  - yarn
  - yarn build
  when:
    branch:
    - v3
- name: Deploy
  image: instrumentisto/rsync-ssh
  commands: 
  - sync ./ /var/wotnlclans
  when:
    branch:
    - v3
  volumes:
  - name: website
    path: /var/wotnlclans

volumes:
- name: website
  host:
    path: /var/www/wotnlclans
