kind: pipeline
name: default

steps:
- name: test
  image: golang
  commands:
  - mkdir -p $GOPATH/src/github.com/mjarkk/wotnlclans
  - export ORIGINALDIR=$(pwd)
  - mv $ORIGINALDIR/* $GOPATH/src/github.com/mjarkk/wotnlclans/
  - cd $GOPATH/src/github.com/mjarkk/wotnlclans
  - go get
  - go build
  - mv $GOPATH/src/github.com/mjarkk/wotnlclans/* $ORIGINALDIR/
  - cd $ORIGINALDIR
  - ls
  when:
    branch:
    - v3
